name: Yocto CI (tmpfs build)

on: [push]

env:
  BUILDDIR: /build
  DL_DIR: /build/downloads
  SSTATE_DIR: /build/sstate-cache
  BB_GENERATE_MIRROR_TARBALLS: 1

  YOCTO_CACHE_HOST: ${{ vars.YOCTO_CACHE_HOST }}
  DL_DIR_REMOTE: rsync://${{ vars.YOCTO_CACHE_HOST }}/downloads
  SSTATE_DIR_REMOTE: rsync://${{ vars.YOCTO_CACHE_HOST }}/sstate-cache
  SOURCE_MIRROR_URL: http://${{ vars.YOCTO_CACHE_HOST }}:8080/downloads/
  SSTATE_MIRRORS: file://.* http://${{ vars.YOCTO_CACHE_HOST }}:8080/sstate-cache/PATH

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Kas (pip only)
        run: pip install --upgrade kas

      - name: Prefetch sources
        continue-on-error: true
        run: kas shell -c "bitbake core-image-base --runall=fetch" pi-minimal.yml

      - name: Build Yocto Project
        run: kas build pi-minimal.yml

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: ${{ env.BUILDDIR }}/tmp/deploy/images/*/*sdimg

      - name: Build Yocto SDK
        run: kas build pi-minimal.yml -c populate_sdk

      - name: Upload SDK
        uses: actions/upload-artifact@v4
        with:
          name: sdk
          path: ${{ env.BUILDDIR }}/tmp/deploy/sdk/*

      - name: Sync DL_DIR + SSTATE to persist
        run: |
          rsync -av --ignore-existing "$DL_DIR/" /persist/downloads/
          rsync -av --ignore-existing "$SSTATE_DIR/" /persist/sstate-cache/

      - name: Upload DL_DIR to cache server
        run: rsync -av --ignore-existing "$DL_DIR/" "$DL_DIR_REMOTE/"

      - name: Upload SSTATE to cache server
        run: rsync -av --ignore-existing "$SSTATE_DIR/" "$SSTATE_DIR_REMOTE/"
