name: Yocto CI

on: [push]

env:
  #BB_NO_NETWORK: "0"               # allow network fetch
  #BB_FETCH_DEBUG: "1"              # debug fetcher
  #BB_VERBOSE_LOGS: "1"             # more detailed logs
  #BITBAKE_UI: "knotty"             # standard output UI
  #BBDEBUG: "2"                     # bitbake debug level (0–2 usually useful)

  #KAS_BUILD_DIR: /build
  #TMPDIR: /build/tmp
  TMPDIR: "/build/tmp-${{ github.run_id }}-${{ github.job }}"
  DL_DIR: /build/downloads
  SSTATE_DIR: /build/sstate-cache

  # fixed cache host
  DL_DIR_REMOTE: "rsync://yocto-cache.m.rasentrimmer.org/downloads"
  SSTATE_DIR_REMOTE: "rsync://yocto-cache.m.rasentrimmer.org/sstate-cache"
  SSTATE_MIRRORS: |
    file://.* http://yocto-cache.m.rasentrimmer.org:8080/sstate-cache/PATH

jobs:
  prepare:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Kas (pip only)
        run: pip install --upgrade kas

      - name: Prefetch sources using premirrors
        continue-on-error: true
        run: |
          set -x
          kas shell -c "bitbake core-image-base --runall=fetch" pi-minimal.yml:premirrors.yml

      - name: Upload DL_DIR to cache server
        run: rsync -av --ignore-existing "$DL_DIR/" "$DL_DIR_REMOTE/"
        if: ${{ always() }} # Run even if previous steps in the job fail or are canceled

      - uses: eviden-actions/clean-self-hosted-runner@v1
        if: ${{ always() }} # Run even if previous steps in the job fail or are canceled

      - name: remove tmp dir
        run: rm -rf $TMPDIR
        if: ${{ always() }} # Run even if previous steps in the job fail or are canceled

  build:
    runs-on: self-hosted
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Kas (pip only)
        run: pip install --upgrade kas

      - name: Build Yocto Project
        run: kas build pi-minimal.yml:force-premirror.yml

      - name: Collect and Compress Artifact
        run: |
          cp ${{ env.TMPDIR }}/deploy/images/*/*.rootfs.*sdimg .
          xz *sdimg

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: ./*.xz

      - name: Upload DL_DIR to cache server
        run: rsync -av --ignore-existing "$DL_DIR/" "$DL_DIR_REMOTE/"
        if: ${{ always() }} # Run even if previous steps in the job fail or are canceled

      - name: Upload SSTATE to cache server
        run: rsync -av --ignore-existing "$SSTATE_DIR/" "$SSTATE_DIR_REMOTE/"
        if: ${{ always() }} # Run even if previous steps in the job fail or are canceled

      - uses: eviden-actions/clean-self-hosted-runner@v1
        if: ${{ always() }} # Run even if previous steps in the job fail or are canceled

      - name: remove tmp dir
        run: rm -rf $TMPDIR
        if: ${{ always() }} # Run even if previous steps in the job fail or are canceled

  sdk:
    runs-on: self-hosted
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Kas (pip only)
        run: pip install --upgrade kas

      - name: Build Yocto SDK
        run: kas build pi-minimal.yml:force-premirror.yml -c populate_sdk

      - name: Upload SDK
        uses: actions/upload-artifact@v4
        with:
          name: sdk
          path: ${{ env.TMPDIR }}/deploy/sdk/*

      - name: Upload DL_DIR to cache server
        run: rsync -av --ignore-existing "$DL_DIR/" "$DL_DIR_REMOTE/"
        if: ${{ always() }} # Run even if previous steps in the job fail or are canceled

      - name: Upload SSTATE to cache server
        run: rsync -av --ignore-existing "$SSTATE_DIR/" "$SSTATE_DIR_REMOTE/"
        if: ${{ always() }} # Run even if previous steps in the job fail or are canceled

      - uses: eviden-actions/clean-self-hosted-runner@v1
        if: ${{ always() }} # Run even if previous steps in the job fail or are canceled

      - name: remove tmp dir
        run: rm -rf $TMPDIR
        if: ${{ always() }} # Run even if previous steps in the job fail or are canceled

  release:
    if: github.ref_type == 'tag'
    runs-on: self-hosted
    needs: [build,sdk]
    steps:
      - uses: actions/download-artifact@v5
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            *xz
            **/*sh
          token: ${{ secrets.RELEASE_TOKEN }}


