name: Yocto CI

on: [push]

env:
  #BB_NO_NETWORK: "0"               # allow network fetch
  #BB_FETCH_DEBUG: "1"              # debug fetcher
  #BB_VERBOSE_LOGS: "1"             # more detailed logs
  #BITBAKE_UI: "knotty"             # standard output UI
  #BBDEBUG: "2"                     # bitbake debug level (0–2 usually useful)

  KAS_BUILD_DIR: /build
  DL_DIR: /build/downloads
  SSTATE_DIR: /build/sstate-cache
  BB_GENERATE_MIRROR_TARBALLS: 1

  # fixed cache host
  DL_DIR_REMOTE: "rsync://yocto-cache.m.rasentrimmer.org/downloads"
  SSTATE_DIR_REMOTE: "rsync://yocto-cache.m.rasentrimmer.org/sstate-cache"
  SSTATE_MIRRORS: |
    file://.* http://yocto-cache.m.rasentrimmer.org:8080/sstate-cache/PATH

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Kas (pip only)
        run: pip install --upgrade kas

      - name: Prefetch sources using premirrors
        continue-on-error: true
        run: |
          set -x
          kas shell -c "bitbake core-image-base --runall=fetch" pi-minimal.yml:premirrors.yml

      - name: Build Yocto Project
        run: kas build pi-minimal.yml

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: ${{ env.KAS_BUILD_DIR }}/tmp/deploy/images/*/*sdimg

      - name: Build Yocto SDK
        run: kas build pi-minimal.yml -c populate_sdk

      - name: Upload SDK
        uses: actions/upload-artifact@v4
        with:
          name: sdk
          path: ${{ env.KAS_BUILD_DIR }}/tmp/deploy/sdk/*

      - name: Sync DL_DIR + SSTATE to persist
        run: |
          echo "[INFO] Syncing tmpfs caches back to /persist..."
          rsync -av --ignore-existing "$DL_DIR/" /persist/downloads/
          rsync -av --ignore-existing "$SSTATE_DIR/" /persist/sstate-cache/

      - name: Upload DL_DIR to cache server
        run: rsync -av --ignore-existing "$DL_DIR/" "$DL_DIR_REMOTE/"

      - name: Upload SSTATE to cache server
        run: rsync -av --ignore-existing "$SSTATE_DIR/" "$SSTATE_DIR_REMOTE/"
